language: minimal
dist: jammy

git:
  depth: 5

jobs:
  include:

  - stage: Static tests
    env:
      - task=shellcheck
    script:
      - shellcheck chkdm
  - stage: Static tests
    language: node_js
    node_js:
      - "18"
    env:
      - task=editorconfig-check
    install:
      - npm i -g echint
    script:
      - echint

  - stage: Ubuntu test
    env:
      - task=Ubuntu-runtime
    before_script:
      - echo $PATH
      - type bash && bash --version
      - echo -e '8.8.4.4\n1.0.0.1\n1.1' > CustomDNS.txt
      - echo -e '223.5.5.5\n114.114.114.114' > CustomDNS2.txt
    script:
      - ./test_chkdm.sh
      - CustomDNSFile=./CustomDNS2.txt ./test_chkdm.sh
      - rm CustomDNS.txt && ./test_chkdm.sh
      - CustomDNSFile=./CustomDNS-not-exist.txt ./test_chkdm.sh

  - stage: Ubuntu test
    env:
      - task=Ubuntu-Make-install-uninstall
    script:
      - sudo make install && ls /usr/local/bin/chkdm
      - sudo make uninstall && ! ls /usr/local/bin/chkdm

  - stage: macOS test
    os: osx
    osx_image: xcode14.2
    env:
      - task=macOS-runtime
    addons:
      homebrew:
        packages:
          - bash
        update: true
    before_script:
      - echo $PATH
      - export PATH="$(brew --prefix)/bin:$PATH"
      - echo $PATH
      - brew info bash
      - which bash
      - env bash --version
      - echo -e '8.8.4.4\n1.0.0.1\n1.1' > CustomDNS.txt
      - echo -e '223.5.5.5\n114.114.114.114' > CustomDNS2.txt
    script:
      - ./test_chkdm.sh
      - CustomDNSFile=./CustomDNS2.txt ./test_chkdm.sh
      - rm CustomDNS.txt && ./test_chkdm.sh
      - CustomDNSFile=./CustomDNS-not-exist.txt ./test_chkdm.sh

  - stage: macOS test
    os: osx
    osx_image: xcode14.2
    env:
      - task=macOS-Make-install-uninstall
    script:
      - sudo make install && ls /usr/local/bin/chkdm
      - sudo make uninstall && ! ls /usr/local/bin/chkdm
