language: minimal
dist: jammy

git:
  depth: 5

jobs:
  include:

  - stage: Static tests
    env:
      - task=shellcheck
    script:
      - shellcheck chkdm
  - stage: Static tests
    language: node_js
    node_js:
      - "18"
    env:
      - task=editorconfig-check
    install:
      - npm i -g echint
    script:
      - echint

  - stage: Ubuntu test
    env:
      - task=Ubuntu-runtime
    before_script:
      - echo $PATH
      - type bash && bash --version
    script:
      - ./chkdm dnslow.me

  - stage: Ubuntu test
    env:
      - task=Ubuntu-Make-install-uninstall
    script:
      - sudo make install && ls /usr/local/bin/chkdm
      - sudo make uninstall && ! ls /usr/local/bin/chkdm

  - stage: macOS test
    os: osx
    osx_image: xcode14.2
    env:
      - task=macOS-runtime
    addons:
      homebrew:
        packages:
          - bash
    before_script:
      - echo $PATH
      - brew info bash
      - which bash
      - env bash --version
    script:
      - ./chkdm dnslow.me

  - stage: macOS test
    os: osx
    osx_image: xcode14.2
    env:
      - task=macOS-Make-install-uninstall
    script:
      - sudo make install && ls /usr/local/bin/chkdm
      - sudo make uninstall && ! ls /usr/local/bin/chkdm
